Add Spectrum IT as platinum sponsor
phphants/php-south-coast-2017 pull request #10
Opened 2017-01-15 21:48 UTC by lboynton

2017-01-16 08:59 UTC, asgrim commented
Just waiting for confirmation on the text to be used.

2017-01-17 17:26 UTC, asgrim requested changes

2017-01-17 17:26 UTC, asgrim commented on sponsors.html
> +                    Spectrum IT Recruitment is an IT &amp; technology focused recruitment consultancy working primarily
Should read: 
> Spectrum IT Recruitment is a specialist provider of IT and Technology recruitment to companies across the Hampshire & the South. Our expertise spans across web development, software engineering and digital environments and we boast a wealth of job opportunities with the region’s leading employers. Spectrum IT is committed to supporting the local IT community, creating a positive experience for job seekers and providing our candidates with the platform to achieve their career goals and aspirations.

2017-01-17 21:22 UTC, lboynton commented on sponsors.html
> +                    Spectrum IT Recruitment is an IT &amp; technology focused recruitment consultancy working primarily
Got rid of the first "the" in 

> the Hampshire & the South

2017-01-17 21:23 UTC, lboynton commented
Forgot to mention, couple of responsiveness improvementness in this as well

2017-01-18 09:15 UTC, asgrim approved these changes

2017-01-18 09:15 UTC, merged

2017-01-18 09:15 UTC, asgrim commented
:+1: