Display sponsors in the footer
phphants/php-south-coast-2017 pull request #19
Opened 2017-03-13 12:11 UTC by lboynton

This gives them a bit more visibility :)

![phpsc-sponsors-footer](https://cloud.githubusercontent.com/assets/98873/23853802/367d700a-07e6-11e7-9618-847c11576eca.png)

Think this looks ok?

2017-03-14 18:23 UTC, asgrim requested changes
Only change I'd suggest is maybe writing in small text "Our generous sponsors make this possible..." or something, just to highlight that they're sponsors. Otherwise it's just a bunch of logos.

2017-03-15 10:45 UTC, lboynton commented
![phpsc-footer-sponsors2](https://cloud.githubusercontent.com/assets/98873/23944902/740460c8-096c-11e7-8a1c-aebe29130c87.png)

2017-03-15 10:55 UTC, asgrim approved these changes

2017-03-15 10:55 UTC, asgrim commented
Yuss, much better :) thanks @lboynton !

2017-03-15 10:55 UTC, merged