Add page for Team
phphants/php-south-coast-2017 pull request #4
Opened 2016-12-06 10:11 UTC by asgrim

Just an idea I had. No idea what it's like on mobile because I suck at doing front end stuff :)

2016-12-10 21:33 UTC, lboynton commented
Twitter links?

2016-12-10 21:42 UTC, lboynton requested changes

2016-12-10 21:42 UTC, lboynton commented on _sass/pages/_team.scss
> +    -moz-border-radius: 10px;
These vendor prefixed versions are quite old now, they aren't needed anymore

2016-12-10 21:42 UTC, lboynton commented on team.html
> +        </div>
To make this responsive, you could try:

```
<div class="row">
    <div class="col-md-2 col-md-offset-1">person1</div>
    <div class="col-md-2">person2</div>
    <div class="col-md-2">person3</div>
    <div class="col-md-2">person4</div>
    <div class="col-md-2">person5</div>
</div>
```

2016-12-10 21:42 UTC, lboynton commented on team.html
> +  role: Speaker
Should this be "Speaker liaison"?

2016-12-10 21:42 UTC, lboynton commented on team.html
> +            folks are core organisation team.
are _part of the_ core organisation team

2016-12-12 18:07 UTC, asgrim commented
@lboynton updated I think :D

2016-12-12 18:42 UTC, lboynton commented
@asgrim can I update this PR?

2016-12-12 18:43 UTC, asgrim commented
@lboynton yes please! :)

2016-12-12 22:28 UTC, lboynton commented
How about something like this?

![Uploading phpsc17-team.png…]()

2016-12-12 22:34 UTC, asgrim commented
Yeah that's better :D hehe

2017-01-07 10:00 UTC, asgrim commented
Is this ready to merge btw?

2017-01-07 19:24 UTC, lboynton commented
No I didn't finish making changes :stuck_out_tongue_closed_eyes: 

Sorry I am on this tomorrow!

2017-01-08 14:46 UTC, lboynton approved these changes

2017-01-08 14:48 UTC, merged